// <auto-generated />
using System;
using ClassLibrary1.DAL.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassLibrary1.DAL.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20240521223243_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary1.DAL.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Quantity = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 2,
                            Quantity = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Quantity = 1,
                            UserId = 0
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 3,
                            Quantity = 4,
                            UserId = 0
                        });
                });

            modelBuilder.Entity("ClassLibrary1.DAL.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 22, 1, 32, 42, 675, DateTimeKind.Local).AddTicks(6780),
                            TotalPrice = 1000m,
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 22, 1, 32, 42, 675, DateTimeKind.Local).AddTicks(6829),
                            TotalPrice = 2000m,
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 5, 22, 1, 32, 42, 675, DateTimeKind.Local).AddTicks(6832),
                            TotalPrice = 3000m,
                            UserId = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 5, 22, 1, 32, 42, 675, DateTimeKind.Local).AddTicks(6834),
                            TotalPrice = 4000m,
                            UserId = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 5, 22, 1, 32, 42, 675, DateTimeKind.Local).AddTicks(6837),
                            TotalPrice = 5000m,
                            UserId = 0
                        });
                });

            modelBuilder.Entity("ClassLibrary1.DAL.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "computers",
                            Description = "Product1",
                            Name = "product1",
                            Price = 2000m,
                            stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = "TV",
                            Description = "Product2",
                            Name = "product2",
                            Price = 4000m,
                            stock = 20
                        },
                        new
                        {
                            Id = 3,
                            Category = "Watches",
                            Description = "Product3",
                            Name = "product3",
                            Price = 2000m,
                            stock = 10
                        },
                        new
                        {
                            Id = 4,
                            Category = "Smart Watches",
                            Description = "Product4",
                            Name = "product4",
                            Price = 2890m,
                            stock = 50
                        },
                        new
                        {
                            Id = 5,
                            Category = "Laptops",
                            Description = "Product5",
                            Name = "product5",
                            Price = 2900m,
                            stock = 90
                        });
                });

            modelBuilder.Entity("ClassLibrary1.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClassLibrary1.DAL.Models.Cart", b =>
                {
                    b.HasOne("ClassLibrary1.DAL.Models.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");

                    b.HasOne("ClassLibrary1.DAL.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassLibrary1.DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassLibrary1.DAL.Models.Order", b =>
                {
                    b.HasOne("ClassLibrary1.DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassLibrary1.DAL.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
